let movieName: string = "Family Man";
let Name = "Alman Ahmad";
let age = 19;
console.log(`My name is ${Name} and I am ${age} years old`);
const mood = true;
let fname = "Alman";
let lname = "Ahmad";
console.log(`${fname + " " + lname}`);
let userAge: number;
userAge = 19;
let product = "Perfume";
let price = 80;
console.log(`This product ${product} costs $${price}`);
let pets: number = 10;
let HBD: boolean = false;
console.log(`The user: ${fname} ${lname} is ${userAge} years old`);
const DOB: number = 2004;
let city: string = "Lahore";
let country: string = "Pakitan";
console.log(`Address: ${city + " " + country}`);
let temp: number;
temp = 24;
